spring:
  application:
    name: todo-app
  # Datasource configuration
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:todo_app}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:todo_app}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# Server configuration
server:
  address: 0.0.0.0
  forward-headers-strategy: native